### ISSUE TITLE
Skill rolls

### ISSUE THREAD

**Issue by Mortium666** [VacantFanatic/SLAfoundry#40]
Skill rolls are supposed to be:

Success Die plus Skill Dice equal to skill ranks+1
Currently only rolling Success Die plus Skill Dice

Would be good to pretty up the results of the skill rolls and include the bonuses/mods like this site does (ie unbelievable successes etc):
http://www.voidstate.com/sla-roller/

**Comment by VacantFanatic** [comment]
I'm actually recoding this from the ground up as the framework I was using made implementing roll cards more difficult.
Re: the plus one you're correct. On p 99 I had read that as the skill die being the +1

**Comment by VacantFanatic** [comment]
Fixed in 0.4.22
