### ISSUE TITLE
Skill names

### ISSUE THREAD

**Issue by Mortium666** [VacantFanatic/SLAfoundry#41]
Some of the skill names aren't 100% the same as those in the books. The drive skill isn't split into Drive Civilian/Pilot and Motorcycle.

**Comment by VacantFanatic** [comment]
I'm re-implementing the skills as Items and this will allow a player to pick a specialization.  Under the current format it creates redundant entries for Drive, Language, Education, Technical.

**Comment by VacantFanatic** [comment]
Will update in 0.6
