### ISSUE TITLE
Adding items

### ISSUE THREAD

**Issue by Mortium666** [VacantFanatic/SLAfoundry#42]
No items listed for the game system. When creating items, not enough fields to add details relevant to combat

**Comment by VacantFanatic** [comment]
The items need to be created to avoid copyright issues.

**Comment by VacantFanatic** [comment]
Can you be more specific about the missing fields?

**Comment by Mortium666** [comment]
At the moment there is just a Description and Attributes field. 
It could be useful to include an item Type (item, vehicle, armour, weapon, ebb equipment, drug, ammunition) and when the item type is selected the relevant fields are available.

For melee weapons you want Skill, DMG, Min DMG, AD and weight
For ranged weapons you want Skill, DMG, Min DMG, AD and weight but also need ROF, Recoil, Range, Clip and Clip Cost
Ammo is possibly difficult, but you would want to be able to select a combination of weapon and Ammo and have the game add the bonuses (ie +1 dmg, +1AD) when combined.
Armour just needs PV, Resistance, Weight
Vehicles might just need stats like Length, Width, Height. Capacity, PV, Resistance, Hitpoints, Movement
Drugs could be hard to implement, not sure. They could work like spells from other games by adding to stats while in effect.

**Comment by VacantFanatic** [comment]
That should be there when an item is created.  I'll have to check as that
*should* be the case?

**Comment by Mortium666** [comment]
Ah, confusion for me is that there are different item types on drop down. There are actually different item types. I'll run through them now and check.

**Comment by VacantFanatic** [comment]
No sweat, I do think currently drugs and vehicles are missing.
Step 1: I'm going to create templates 
Step 2 I'll see about tying active effects into the drug items which should then show up in the effects tab
![image](https://github.com/VacantFanatic/SLAfoundry/assets/5420476/fe1c27c6-e163-4803-b76b-5c3b79212d7d)

**Comment by Mortium666** [comment]
I just created a formulae (Detect Ebb). There's no way to roll it. When clicking on the item, it takes you to Edit item instead of being rollable

**Comment by Mortium666** [comment]
Created a melee weapon (GASH Chain Axe). There is no skill called polearm in the drop down menu for the appropriate skill to attach it to.
